import { ArrowLeft, Pencil } from "lucide-react";
import { useState } from "react";
import { calculateCoreProgress, type Mandalart } from "../lib/mandalart";
import { ProgressRing } from "./progress-ring";
interface Props { mandalart: Mandalart; selectedCoreId: string | null; onSelectCore: (coreId: string | null) => void; onUpdateCenter: (text: string) => void; onUpdateCore: (coreId: string, text: string) => void; onUpdateAction: (coreId: string, actionId: string, text: string) => void; onToggleAction: (coreId: string, actionId: string) => void; }
export function FocusEditor({ mandalart, selectedCoreId, onSelectCore, onUpdateCenter, onUpdateCore, onUpdateAction, onToggleAction }: Props) {
  const [editingCoreId, setEditingCoreId] = useState<string | null>(null);
  const [draft, setDraft] = useState("");
  const core = mandalart.coreGoals.find((item) => item.id === selectedCoreId) ?? null;
  const saveDraft = (coreId: string) => { onUpdateCore(coreId, draft); setEditingCoreId(null); };
  if (!core) return <section className="editor-card" aria-labelledby="editor-title"><div className="section-heading"><div><span className="eyebrow">중심 설계</span><h2 id="editor-title">큰 목표와 8가지 방향</h2></div></div><label className="center-input-label">내가 이루고 싶은 가장 큰 목표<input value={mandalart.centerGoal} onChange={(event) => onUpdateCenter(event.target.value)} placeholder="예: 더 나은 나 만들기" /></label><div className="focus-grid center-focus">{mandalart.coreGoals.map((item, index) => <div className={`goal-card-row tone-${item.colorKey}`} key={item.id}>{editingCoreId === item.id ? <input autoFocus aria-label={`핵심 목표 ${index + 1}`} value={draft} onChange={(event) => setDraft(event.target.value)} onBlur={() => saveDraft(item.id)} onKeyDown={(event) => { if (event.key === "Enter") saveDraft(item.id); if (event.key === "Escape") setEditingCoreId(null); }} /> : <button className="goal-open-button" type="button" aria-label={`${item.title || "이름 없는 목표"} 세부 계획 열기`} onClick={() => onSelectCore(item.id)}><span>{String(index + 1).padStart(2, "0")}</span><strong>{item.title || "핵심 목표"}</strong></button>}<button className={`goal-edit-button tone-${item.colorKey}`} type="button" aria-label={`${item.title || "이름 없는 목표"} 이름 수정`} onMouseDown={(event) => event.preventDefault()} onClick={() => { setDraft(item.title); setEditingCoreId(item.id); }}><Pencil size={15} /></button></div>)}</div></section>;
  return <section className={`editor-card tone-border-${core.colorKey}`} aria-labelledby="editor-title"><button className="back-to-center" type="button" onClick={() => onSelectCore(null)}><ArrowLeft size={15} /> 중심 설계로 돌아가기</button><div className="section-heading editor-heading"><div><span className="eyebrow">집중 영역</span><h2 id="editor-title">{core.title || "이름 없는 목표"} 세부 계획</h2></div><ProgressRing value={calculateCoreProgress(core)} label="영역 달성" /></div><label className={`center-input-label tone-${core.colorKey}`}>핵심 목표<input value={core.title} onChange={(event) => onUpdateCore(core.id, event.target.value)} placeholder="핵심 목표를 입력하세요" /></label><div className="focus-grid">{core.actions.map((action, index) => <div className={`action-row ${action.completed ? "completed" : ""}`} key={action.id}><input type="checkbox" checked={action.completed} disabled={!action.text.trim()} onChange={() => onToggleAction(core.id, action.id)} aria-label={`${action.text || `실행 항목 ${index + 1}`} 완료`} /><label><span>{String(index + 1).padStart(2, "0")}</span><input aria-label={`실행 항목 ${index + 1}`} value={action.text} onChange={(event) => onUpdateAction(core.id, action.id, event.target.value)} placeholder="구체적인 행동을 적어보세요" /></label></div>)}</div></section>;
}
